### ISSUE TITLE
Tests panic when run twice in a row without restarting fuel node

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/sway#2969]
```
$ RUST_BACKTRACE=1 cargo run --bin=test
... <output skipped> ...
Contract id: 0xda0aa9fce0e09044c49954b15d9243bedf40c97e8d64be5c36de4b2d25b1a43a
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Response errors; Transaction id was already used: 0x513d6e09ec473cf71d4587b6a000ec08e0adb8037b0b73b169b22db096f64d94', test/src/e2e_vm_tests/harness.rs:35:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1107:23
   4: test::e2e_vm_tests::harness::deploy_contract
             at ./test/src/e2e_vm_tests/harness.rs:23:5
   5: test::e2e_vm_tests::run::{{closure}}::{{closure}}
             at ./test/src/e2e_vm_tests/mod.rs:151:33
   6: std::collections::hash::map::Entry<K,V>::or_insert_with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/collections/hash/map.rs:2549:43
   7: test::e2e_vm_tests::run::{{closure}}
             at ./test/src/e2e_vm_tests/mod.rs:148:26
   8: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/iter/adapters/map.rs:84:28
   9: core::iter::traits::iterator::Iterator::fold
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/iter/traits/iterator.rs:2414:21
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/iter/adapters/map.rs:124:9
  11: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/iter/traits/iterator.rs:831:9
  12: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/vec/spec_extend.rs:40:17
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  14: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/vec/in_place_collect.rs:164:20
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/vec/mod.rs:2648:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/iter/traits/iterator.rs:1836:9
  17: test::e2e_vm_tests::run
             at ./test/src/e2e_vm_tests/mod.rs:145:36
  18: test::main
             at ./test/src/main.rs:20:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Some comments from an internal discussion:

> This is related to transaction ID collision. When you run the same script twice, for example, you generate the same transaction ID and that causes collisions. Same happens when you try to deploy the same contract twice.

> We should make the tx ids unique

**Comment by otrho** [comment]
Unfortunately there are some E2E tests where we hardcode the contract IDs.  This in itself is painful and why we usually try to write those tests using the SDK.  But they're still there for now.

So if we were to introduce salting the keys then I think that'd all break...  I'm no expert on that side of things though.
