### ISSUE TITLE
`forc tx --help` prints help successfully but within a `panic!` message

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3886]
This is due to the current way we attempt to parse the trailing chain of `input`s and `output`s.

Until this is addressed, we'll need to omit this from the Sway book's Forc Plugins section as the mdbook-forc-documenter plugin uses the `--help` output to generate docs.

This is further motivation for #3804, ideally so that we can just call `Command::parse` at the top-level like a normal clap application and get regular coloured help output.

**Comment by bingcicle** [comment]
Was going to open an issue for this but this is probably related. Tried executing `forc tx` plainly and got this:

```console
$ forc tx
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: forc-tx 0.33.1
A `forc` plugin for constructing transactions.

USAGE:
    forc-tx [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -h, --help                         Print help information
    -o, --output-path <OUTPUT_PATH>    
    -V, --version                      Print version information

SUBCOMMANDS:
    create    Construct a `Create` transaction for deploying a contract
    help      Print this message or the help of the given subcommand(s)
    mint      Construct a `Mint` transaction for emulating a block producer
    script    Construct a `Script` transaction for running a script
', forc-plugins/forc-tx/src/main.rs:2:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   3: forc_tx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
